#ifndef NOPOISONDIALOGUE_VERSION_INCLUDED
#define NOPOISONDIALOGUE_VERSION_INCLUDED

#define NOPOISONDIALOGUE_MAKE_STR_HELPER(x) #x
#define NOPOISONDIALOGUE_MAKE_STR(x) NOPOISONDIALOGUE_MAKE_STR_HELPER(x)

#define NOPOISONDIALOGUE_VERSION_MAJOR		1
#define NOPOISONDIALOGUE_VERSION_MINOR		2
#define NOPOISONDIALOGUE_VERSION_PATCH		3
#define NOPOISONDIALOGUE_VERSION_BETA		0
#define NOPOISONDIALOGUE_VERSION_VERSTRING	NOPOISONDIALOGUE_MAKE_STR(NOPOISONDIALOGUE_VERSION_MAJOR) "." NOPOISONDIALOGUE_MAKE_STR(NOPOISONDIALOGUE_VERSION_MINOR) "." NOPOISONDIALOGUE_MAKE_STR(NOPOISONDIALOGUE_VERSION_PATCH) "." NOPOISONDIALOGUE_MAKE_STR(NOPOISONDIALOGUE_VERSION_BETA)

#endif
